from app.models.locations import DimLocations
from app.models.parts import DimParts
from app.models.purchases import DimPurchases
from app.models.supplier import DimSupplier
from app.models.vehicle import DimVehicle
from app.models.warranties import FactWarranties
from app.models.warranties import FactWarranties
from app.models.user import User
from app.models.vehicle import PropulsionType
